'use strict';
const steps = [
  {title:'Meet your next paper flyer', short:'Get ready', phase:'Before you fold', image:24, pair:false, text:'Grab one rectangular sheet: 8½ × 11 inches or 9 × 12 inches. We use white paper so the folds and layers are easy to see. Find a flat surface and let’s begin.', caption:'Your destination: a broad-winged paper bat. No scissors, tape, or glue needed.', check:'One rectangular sheet and a clear place to fold. Keep the reference photos facing the same way as your paper.', tip:'Construction paper is a good starting point. Thick cardstock takes more effort to crease. Work slowly and press each crease firmly with a fingertip.'},
  {title:'Make your center crease', short:'Center crease', phase:'01 / Build the base', image:1, pair:true, text:'Place the paper with a long edge along the bottom. Bring the left edge over to the right edge, fold in half, and press the crease. Open it flat again.', caption:'Left: the starting rectangle. Right: opened flat with a vertical center crease.', check:'You have one crease dividing the rectangle into equal left and right halves.', tip:'Match the corners before pressing the fold. This center line is your guide for the next few steps.'},
  {title:'Bring both sides to the middle', short:'Sides to center', phase:'01 / Build the base', image:3, pair:true, text:'Fold the left edge inward until it meets the center crease. Repeat with the right edge. Leave both flaps folded in.', caption:'Work one side at a time, then compare your two folded panels with the right photo.', check:'Both inner edges meet at the center, like a pair of closed doors.', tip:'Aim for the edges to meet rather than overlap. Keep the top and bottom edges aligned.'},
  {title:'Fan the lower sides outward', short:'Fan out the sides', phase:'01 / Build the base', image:5, pair:true, text:'Take the inner edge of the right flap and fold it diagonally outward. Keep the top near the center while the bottom swings out to the right. Repeat on the left to make a matching flare.', caption:'Left: one flap folded outward. Right: both flaps flare out, wider at the bottom.', check:'The top stays narrow and the bottom spreads wide. The two diagonal folds mirror each other.', tip:'This is a diagonal fold, not a straight accordion fold. Tap “Right detail” for a larger view of the finished shape, and match the slope on both sides.'},
  {title:'Fold down the top corners', short:'Top corners', phase:'02 / Shape the bat', image:7, pair:true, text:'Fold the upper-right corner diagonally down toward the middle, like the nose of a paper airplane. Repeat with the upper-left corner to make a point at the top.', caption:'Left: the first corner folded. Right: both corners form a pointed roof.', check:'A centered point at the top, with matching triangular folds on either side.', tip:'Keep the flared lower sides from the previous step in place. Only the top corners move here.'},
  {title:'Flip over. Bring the point down.', short:'Flip & fold down', phase:'02 / Shape the bat', image:9, pair:true, text:'Turn the whole model over from left to right, keeping the point at the top. Then fold that top point downward to the bottom edge. Press the new horizontal crease.', caption:'Left: the back of the model after turning it over. Right: the top point folded down.', check:'The point faces down, and the whole model is much shorter and wider.', tip:'Turning over means showing the back face, not rotating the paper on the table. The left photo shows the face you should see before folding.'},
  {title:'Fold the small upper corners', short:'Small corner folds', phase:'02 / Shape the bat', image:11, pair:true, text:'Fold the small upper-right corner diagonally down. Repeat on the upper-left corner. Use the photos to match the small sloping shoulders, while leaving the big downward-pointing flap in place.', caption:'Left: one small upper corner folded. Right: both small corners folded down.', check:'The two upper outside corners slope down symmetrically. The large center point still faces down.', tip:'These folds are at the upper outer corners, behind the large center flap. Don’t fold the big wing tips into the middle. Enlarge the photo if the dark layers are hard to distinguish.'},
  {title:'Lift the point, then flip over', short:'Point up & flip', phase:'02 / Shape the bat', image:13, pair:true, text:'Fold the large downward point back upward so it covers the two small corners you just folded. Then turn the whole model over again, keeping the point at the top.', caption:'Left: the point folded back up. Right: the model after turning it over.', check:'On the new face, a small triangle sticks up above the straight top edge.', tip:'First do the fold shown on the left; only then flip to the back face shown on the right. The triangle helps hold the layers together.'},
  {title:'Fold the point down; close in half', short:'Close the body', phase:'03 / Ready for flight', image:15, pair:true, text:'Fold the small top triangle downward over the straight edge. Now fold the whole model in half along its original center crease, bringing the left and right wings together.', caption:'Left: the little point folded down. Right: the model folded in half, with the wings stacked.', check:'Your model is now half as wide, with the two wings lined up on top of each other.', tip:'The second fold is along the vertical center line, not from top to bottom. Keep the small folded triangle on the outside, as shown in the photo.'},
  {title:'Give your bat its wings', short:'Fold the wings', phase:'03 / Ready for flight', image:17, pair:true, text:'Fold one wing down, leaving a narrow strip of body underneath to hold. Turn the model over and make the same wing fold on the other side. Gently open the wings out.', caption:'Left: one wing folded down. Right: both wings opened, with a raised center body.', check:'Both wings are the same size and angle, with a small grip beneath the center.', tip:'Match the second wing fold to the first. Don’t fold right at the bottom edge—you need a little body to pinch between your fingers.'},
  {title:'Time for a test flight', short:'Take flight!', phase:'04 / Test pilot', image:20, pair:false, text:'Hold the little body underneath with your thumb and finger. Open the wings evenly, point the nose forward, and give it a gentle, level toss into a clear space.', caption:'Grip the center body underneath, rather than pinching a wing.', check:'Wings look balanced, creases are firm, and the path ahead is clear.', tip:'Try these extra flight-tuning tips: if it rolls to one side, check that both wings have equal angles. If it dives, try a gentler toss and tiny upward bends at the back edges. Change just one thing between test flights.'}
];
const $ = id => document.getElementById(id);
const storageKey = 'flying-bat-v1';
let state = {step:0, done:[]};
try { const saved=JSON.parse(localStorage.getItem(storageKey)); if(saved && Number.isInteger(saved.step) && saved.step>=0 && saved.step<steps.length) state={step:saved.step,done:Array.isArray(saved.done)?saved.done.filter(n=>Number.isInteger(n)&&n>=0&&n<steps.length):[]}; } catch {}
let view='both';
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{$('save-status').textContent='Progress is available for this visit only.';}}
function photoView(value){view=value;const s=steps[state.step];$('photo').className='photo'+(s.pair&&value!=='both'?' detail '+value:'');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===value)));}
function render(){
  const s=steps[state.step];
  window.BatAnimation.setStep(state.step);
  $('title').textContent=s.title;$('instruction').textContent=s.text;$('phase').textContent=s.phase;
  $('number').textContent=state.step===0?'GET READY':`STEP ${state.step} OF ${steps.length-1}`;
  $('check').textContent=s.check;$('tip').textContent=s.tip;$('caption').textContent=s.caption;
  $('image').src=`assets/bat-${s.image}.jpg`;$('image').alt=s.caption;
  $('panels').hidden=!s.pair;photoView('both');$('help').open=false;
  $('progress').style.width=`${state.done.length/steps.length*100}%`;
  $('count').textContent=`${state.done.length}/${steps.length}`;
  $('back').disabled=state.step===0;$('next').textContent=state.step===0?'Let’s fold →':state.step===steps.length-1?(state.done.includes(state.step)?'Finished ✓':'My bat is ready! ✓'):'Got it. Next →';
  $('next').disabled=state.step===steps.length-1&&state.done.includes(state.step);
  $('nav-count').textContent=`${state.step+1} / ${steps.length}`;
  $('celebration').hidden=!(state.step===steps.length-1&&state.done.includes(state.step));
  $('steps').replaceChildren(...steps.map((s,i)=>{const b=document.createElement('button');b.type='button';b.className=state.done.includes(i)?'done':'';b.setAttribute('aria-label',`${i===0?'Preparation':'Step '+i}: ${s.short}${state.done.includes(i)?', completed':''}`);if(i===state.step)b.setAttribute('aria-current','step');const dot=document.createElement('span');dot.className='step-dot';dot.textContent=state.done.includes(i)?'✓':i===0?'•':String(i);const label=document.createElement('span');label.className='step-name';label.textContent=s.short;b.append(dot,label);b.onclick=()=>go(i);return b;}));
  const active=$('steps').querySelector('[aria-current]');if(innerWidth<=800)$('steps').scrollLeft=active.offsetLeft-$('steps').offsetLeft-10;
  if(state.step+1<steps.length){const img=new Image();img.src=`assets/bat-${steps[state.step+1].image}.jpg`;}
  save();
}
function go(index){if(index<0||index>=steps.length)return;if('speechSynthesis' in window)speechSynthesis.cancel();$('speak').textContent='♪ Read aloud';state.step=index;render();if(innerWidth<=800&&scrollY>350)document.querySelector('.lesson').scrollIntoView({block:'start'});}
function next(){if(state.step===steps.length-1&&state.done.includes(state.step))return;if(!state.done.includes(state.step))state.done.push(state.step);go(Math.min(state.step+1,steps.length-1));}
function restart(){if(!confirm('Start a fresh bat and clear your saved progress?'))return;state={step:0,done:[]};go(0);}
$('back').onclick=()=>go(state.step-1);$('next').onclick=next;$('restart').onclick=restart;$('again').onclick=restart;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>photoView(b.dataset.view));
$('photo').onclick=()=>{$('large-image').src=$('image').src;$('large-image').alt=$('image').alt;$('viewer-title').textContent=steps[state.step].title;$('viewer').showModal();};
$('close-viewer').onclick=()=>$('viewer').close();
$('viewer').addEventListener('click',e=>{if(e.target===$('viewer')){const r=$('viewer').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('viewer').close();}});
document.addEventListener('keydown',e=>{if($('viewer').open||$('film-viewer').open||e.altKey||e.ctrlKey||e.metaKey||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();go(state.step+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(state.step-1);}});
if(!('speechSynthesis' in window))$('speak').hidden=true;
$('speak').onclick=()=>{if(speechSynthesis.speaking){speechSynthesis.cancel();$('speak').textContent='♪ Read aloud';return;}const s=steps[state.step];const voice=new SpeechSynthesisUtterance(`${s.title}. ${s.text} Quick check: ${s.check}`);voice.lang='en-US';voice.rate=.9;voice.onend=voice.onerror=()=>{$('speak').textContent='♪ Read aloud';};$('speak').textContent='■ Stop reading';speechSynthesis.speak(voice);};
render();
